### ISSUE TITLE
how can I get the training matlab code?

### ISSUE THREAD

**Issue by sophiatse** [AmrSaleh/KinectOnlineActionDetection#1]
Sir,I 'm reading the paper .I saw the paper says I can get the matlab code at the authors's website.But I didn't find it ,can you please share the code to me ?
Thanks advanced.

**Comment by AbdelrahmanAli** [comment]
Kindly contact Eng. Moustafa Meshry for the Matlab code. He is the author of the paper.

https://scholar.google.com.eg/citations?user=nf7lnq4AAAAJ&hl=en

**E-mail:** mmeshry@cs.umd.edu

**Comment by sophiatse** [comment]
thanks for your reply
